export const V = {
  bg: "#FAF8F5",
  card: "#FFFFFF",
  cardHover: "#F5F2EE",
  text: "#6B6560",
  dim: "#8A857F",
  muted: "#B0AAA3",
  bright: "#1A1714",
  accent: "#A01C2D",
  accentLit: "#C8354A",
  accentDim: "rgba(160,28,45,0.06)",
  accentGlow: "rgba(160,28,45,0.12)",
  border: "rgba(0,0,0,0.07)",
  borderHover: "rgba(0,0,0,0.14)",
  divider: "rgba(0,0,0,0.06)",
  radius: 16,
  radiusSm: 10,
  heading: "'Unbounded', sans-serif",
  body: "'Manrope', -apple-system, sans-serif",
};

export const cases = [
  {
    slug: "object-first",
    client: "Object First → Veeam", tag: "SaaS · DATA PROTECTION · EXIT", result: "EXIT", resultLabel: "acquired by Veeam",
    color1: "#1a1a2e", color2: "#16213e", color3: "#0f3460", accent: "#e94560",
    metrics: [{ v: "2+ года", l: "контракт" },{ v: "$100K+", l: "бюджет проекта" },{ v: "Veeam", l: "приобретена" }],
    desc: "Стартап в сфере ransomware-proof backup storage. Мы были единственной внешней командой на дизайне и разработке на протяжении 2+ лет. Компания была приобретена Veeam — мировым лидером рынка data protection.",
    scope: ["UI/UX Design", "Figma", "HubSpot CMS", "Веб-разработка", "Landing Pages", "Investor Decks", "One-Pagers", "Marketing Materials"],
    detail: {
      challenge: "Object First — стартап из Бостона, создающий ransomware-proof backup storage appliance (Ootbi). Продукт на стыке cybersecurity и data protection. Внутренней дизайн-команды нет, но нужна была полная дизайн- и веб-инфраструктура: брендинг, маркетинговый сайт, продуктовые страницы, материалы для инвесторов и партнёров. Мы стали единственным внешним партнёром по дизайну и фронтенд-разработке.",
      solution: [
        { title: "UI/UX дизайн и бренд-система", text: "Разработали полную дизайн-систему в Figma: компоненты, типографика, цветовая палитра, иконки. Создавали продуктовые лендинги, feature pages, сравнительные таблицы с конкурентами, презентации для инвесторов, partner one-pagers, case study templates и все маркетинговые материалы." },
        { title: "Веб-разработка на HubSpot CMS", text: "Построили маркетинговый сайт с нуля на HubSpot CMS: кастомные модули, blog templates, gated content pages, интеграция с HubSpot CRM для lead capture. Регулярные обновления под каждый продуктовый релиз, A/B тесты лендингов, оптимизация Core Web Vitals." },
        { title: "Embedded-команда на 2+ года", text: "Работали как выделенная команда: 100–120 часов в месяц, ежедневные стендапы, полное погружение в продукт и roadmap. Часовая модель ($50/час) при стабильной загрузке позволила масштабироваться под задачи — от тихих недель до интенсивных спринтов перед launch events." },
        { title: "Результат: EXIT → Veeam", text: "Object First была приобретена Veeam — мировым лидером в сфере backup и data protection с оценкой $15B+. Качество дизайна, маркетинговых материалов и веб-присутствия сыграло прямую роль в позиционировании компании перед сделкой." },
      ],
      results: [{ v: "EXIT", l: "приобретена Veeam ($15B+)" },{ v: "2+ лет", l: "непрерывный контракт" },{ v: "100–120ч/мес", l: "стабильная загрузка" },{ v: "$100K+", l: "общий бюджет проекта" }],
    },
  },
  {
    slug: "ak-cabinet",
    client: "AK Cabinet Craft", tag: "MANUFACTURING · B2C · REVENUE SHARE", result: "3%", resultLabel: "revenue share",
    color1: "#2d2d2d", color2: "#4a3728", color3: "#6b4423", accent: "#c8935f",
    metrics: [{ v: "Чикаго", l: "рынок" },{ v: "3%", l: "от выручки" },{ v: "Full-cycle", l: "с нуля" }],
    desc: "Revenue-share партнёрство с производителем кастомных кухонь и шкафов в Чикаго. Построили весь маркетинг с нуля — от Google Ads и SEO до офлайн-каналов и CRM. Работаем за 3% от выручки вместо фиксированного ретейнера.",
    scope: ["Google Ads", "Local Services Ads", "SEO", "Google Business Profile", "HubSpot CRM", "Email Sequences", "Контент-маркетинг", "Postcards", "Партнёрства с дизайнерами"],
    detail: {
      challenge: "AK Cabinet Craft — семейный производитель кастомных кухонь и шкафов в Чикаго. Средний чек $15K–$40K. До нас клиенты приходили только по сарафану и рефералам от подрядчиков. Онлайн-присутствия ноль: нет рекламы, нет SEO, нет CRM. Нужна была полная маркетинговая инфраструктура — но бюджета на крупный ретейнер не было. Мы предложили revenue share модель.",
      solution: [
        { title: "Revenue Share модель (3%)", text: "Вместо фиксированного ретейнера — 3% от закрытых сделок. Мы инвестируем своё время, экспертизу и рекламный бюджет; зарабатываем только когда клиент зарабатывает. Полное совпадение интересов — мы заинтересованы не в лидах, а в закрытых продажах." },
        { title: "Google Ads + Local Services Ads", text: "Запустили Search-кампании и LSA, нацеленные на homeowners в Чикаго и пригородах с высоким доходом. Ключевые запросы: custom kitchen cabinets, cabinet refacing, kitchen remodel Chicago. Постоянная оптимизация по стоимости лида и квалификации заявок — отсекаем нецелевые обращения." },
        { title: "SEO + Google Business Profile", text: "Полная оптимизация GBP: регулярные посты, ответы на отзывы, фотографии реальных проектов до/после. SEO: технический аудит, оптимизация мета-тегов, создание location pages под Chicago suburbs, блог с kitchen renovation guides. Цель — доминировать в Local Pack." },
        { title: "HubSpot CRM + Email + Offline", text: "Внедрили HubSpot: pipeline по этапам (lead → estimate → signed → completed), автоматические follow-up sequences, lead scoring. Email-маркетинг: nurture-серия для тех, кто запросил estimate но не подписал. Offline: direct mail postcards по целевым zip-кодам, партнёрства с interior designers и general contractors." },
      ],
      results: [{ v: "3%", l: "revenue share вместо ретейнера" },{ v: "Full-cycle", l: "маркетинг полного цикла с нуля" },{ v: "HubSpot", l: "CRM + pipeline + автоматизация" },{ v: "Online + Offline", l: "Ads + SEO + GBP + Email + Direct Mail" }],
    },
  },
  {
    slug: "sos-moving",
    client: "SOS Moving → AI Moving", tag: "LOGISTICS · AI SaaS · PERFORMANCE", result: "$14.6M", resultLabel: "в продажах",
    color1: "#0a1628", color2: "#1a2744", color3: "#243b63", accent: "#4facfe",
    metrics: [{ v: "10,235", l: "заказов" },{ v: "$400K+", l: "рекламный бюджет" },{ v: "AI SaaS", l: "продукт" }],
    desc: "Два этапа: performance-маркетинг, который принёс $14.6M в продажах и 10,235 заказов для мувинговой компании. Затем — трансформация накопленной экспертизы в AI SaaS-продукт для всей индустрии переездов.",
    scope: ["Google Ads", "Performance Max", "SEO", "Schema Markup", "GA4", "CallRail", "HubSpot CRM", "Lead Scoring", "AI Development", "SaaS"],
    detail: {
      challenge: "SOS Moving — мувинговая компания в конкурентном рынке. Проблемы: нет маркетинговой системы, высокая стоимость лида, нет трекинга звонков, CRM ведётся в таблицах. Цель первого этапа — построить прибыльную машину лидогенерации. Цель второго — превратить накопленный опыт и данные в отдельный AI SaaS-продукт для всей индустрии.",
      solution: [
        { title: "Google Ads: Search + PMax", text: "Запустили и масштабировали Search и Performance Max кампании. $400K+ рекламного бюджета под управлением. Разделение по типам переезда (local, long-distance, commercial), гео-таргетинг, негативные ключевые слова. Постоянная оптимизация ставок и креативов — снижение CPA при росте объёма заказов." },
        { title: "SEO + контент-стратегия", text: "Полный технический аудит: исправление crawl errors, canonical tags, page speed. Новая архитектура сайта: service pages по типам переезда, location pages по городам. Schema markup (LocalBusiness, FAQ, Review). Контент-стратегия: moving guides, cost calculators, checklists — контент на каждый этап воронки." },
        { title: "Сквозная аналитика и CRM", text: "Интеграция GA4 + CallRail + HubSpot в единую систему. Каждый звонок записывается, привязывается к keyword и campaign. HubSpot: кастомный pipeline, автоматические follow-up sequences, lead scoring по размеру переезда и срочности. Клиент видит реальный ROI по каждому каналу в реальном времени." },
        { title: "AI Moving — SaaS-продукт", text: "На основе 10K+ обработанных заказов и накопленных данных создали AI Moving — AI-платформу для мувинговых компаний. Автоматическая оценка стоимости по фото, оптимизация маршрутов, AI-чатбот для квалификации лидов, predictive analytics по загрузке. Из клиентского проекта — в самостоятельный продукт." },
      ],
      results: [{ v: "$14.6M", l: "общий объём продаж клиента" },{ v: "10,235", l: "выполненных заказов" },{ v: "$400K+", l: "рекламный бюджет под управлением" },{ v: "AI SaaS", l: "собственный продукт из экспертизы" }],
    },
  },
  {
    slug: "rocs",
    client: "R.O.C.S.", tag: "FMCG · ENTERPRISE · BRAND DESIGN", result: "2+ года", resultLabel: "партнёрство",
    color1: "#1a2e1a", color2: "#2d4a2d", color3: "#1e6040", accent: "#6bcf7f",
    metrics: [{ v: "Enterprise", l: "масштаб" },{ v: "3 бренда", l: "R.O.C.S. / Splat / BioMio" },{ v: "360°", l: "дизайн" }],
    desc: "Дизайн-партнёрство с одним из крупнейших FMCG-холдингов России (Splat Global). Поддержка трёх брендов с разным позиционированием: R.O.C.S., Splat, BioMio — от упаковки и key visuals до digital-кампаний и ритейл-материалов.",
    scope: ["Brand Design", "Key Visual", "Упаковка", "POS-материалы", "Digital-кампании", "SMM-контент", "Промо-лендинги", "Ритейл-оформление"],
    detail: {
      challenge: "R.O.C.S. — часть группы компаний Splat Global, один из крупнейших FMCG-холдингов России. Три бренда с принципиально разным позиционированием: R.O.C.S. (премиум oral care, высокая наценка), Splat (масс-маркет, широкая дистрибуция), BioMio (эко-сегмент, осознанное потребление). Нужна была внешняя дизайн-команда, способная работать на enterprise-уровне: быстрые сроки, корпоративные согласования, множество стейкхолдеров, работа по brand guidelines каждого бренда.",
      solution: [
        { title: "Brand Design для 3 брендов", text: "Работали параллельно с R.O.C.S., Splat и BioMio. Разрабатывали key visuals для сезонных кампаний, адаптации под разные каналы и форматы. Каждый бренд — свой tone of voice, своя цветовая палитра, свои правила. Переключение между брендами в рамках одного дня." },
        { title: "Упаковка и ритейл", text: "Дизайн упаковки для новых SKU, обновление существующих линеек. POS-материалы: шелфтокеры, воблеры, стенды. Оформление полок для федеральных сетей (Магнит, Пятёрочка, Перекрёсток). Адаптация под требования международных рынков — разные языки, разные регуляции." },
        { title: "Digital-кампании и контент", text: "Креативы для performance-рекламы (ВК, Яндекс, Google), SMM-контент для трёх аккаунтов параллельно, промо-лендинги под акции и новинки. Быстрый цикл: от брифа до финального материала за 2–5 дней. Баннеры, сторис, reels, email-шаблоны." },
        { title: "Enterprise-процессы", text: "Встроились в корпоративную структуру: регулярные созвоны, работа через корпоративный таск-трекер, согласования с brand-менеджерами и product-менеджерами. Строгое следование brand guidelines каждого бренда. Стабильное партнёрство 2+ года без перерывов." },
      ],
      results: [{ v: "3 бренда", l: "R.O.C.S. / Splat / BioMio" },{ v: "2+ лет", l: "непрерывное партнёрство" },{ v: "360°", l: "от упаковки до digital" },{ v: "Enterprise", l: "корпоративный масштаб и процессы" }],
    },
  },
];
